### ISSUE TITLE
Cannot open pdf on Android 11

### ISSUE THREAD

**Issue by BrunoKarriqi** [RonRadtke/react-native-blob-util#101]
react 17.0.2
react-native 0.66.2
react-native-blob-util 0.13.16

it works very fine on Android 9 or lower but it doesn't work on Android 11

**Comment by RonRadtke** [comment]
Any errors? Do you have installed an app to open a pdf?
On my Android 11 device it works fine

**Comment by BrunoKarriqi** [comment]
Yes i do have a reader, and i don't se any errors.

**Comment by RonRadtke** [comment]
@BrunoKarriqi just saw it no, sorry. Could you please update to the current version?
0.13.18 has a fix for the intent on newer android versions. So please check if it works with the current version

**Comment by RonRadtke** [comment]
@BrunoKarriqi found another issue. 
Where do you save the pdf to? Apps internal storage?
You can simply post the path you try to open here. Because currently the lib is not able to open mediastore content uris.
Just checking if i fix it with the upcoming 0.14.0 or if I should squeeze a hotfix inbetween

**Comment by RonRadtke** [comment]
@BrunoKarriqi I released 0.14.0 yesterday. It fixed the issue for me, at least if I download to the mediastore.

**Comment by BrunoKarriqi** [comment]
@RonRadtke thanx a lot, im closing the issue
