### ISSUE TITLE
Android crash -  Illegal callback invocation from native module  - RuntimeException firing twice

### ISSUE THREAD

**Issue by scgough** [RonRadtke/react-native-blob-util#113]
I've been trying to get to the bottom of this issue. I've seen it over on the old repo and there's not been a good solution for it.

On certain devices...namely Realme, Oppo and Huawei a regular crash seems to be occurring. I've tested using a "Realme 7" phone, Android 11 and can reproduce it every time w/ the below scenario.

 
The issue seems to be triggered if you re-download a previously downloaded item again and you have `addAndroidDownloads: path` set.  

Upon completing the 2nd download `onReceive` seems to fire twice. 
The following line is called: 
https://github.com/RonRadtke/react-native-blob-util/blob/e73e2791890fa02066ac89fb4cfaad7cfb47772c/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java#L804

At this point in time `this.callback.mInvoked` is true which fires an exception taking you to line 808 which attempts to fire another callback and causes the crash:
https://github.com/RonRadtke/react-native-blob-util/blob/e73e2791890fa02066ac89fb4cfaad7cfb47772c/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java#L808

I can get this issue to stop happening if I change the `path` supplied to be unique so I'm wondering if this is something to do with this value or maybe the source file Url? 

I'd love to figure out exactly why this is happening! Has anyone else seen this?

**Comment by RonRadtke** [comment]
The problem is actually that it is called twice. Since react-native is not allowing the fire the callback twice.
Most likely this is caused by the device triggering multiple ``DownloadManager.ACTION_DOWNLOAD_COMPLETE``
Probably you could even see these events in logcat.

I assume it's related to this bug here: https://issuetracker.google.com/issues/36930682#c13

The problem arises with fixing this issue. Probably we could implement  a flag making sure the method is only called once - or just trying to catch the ``RuntimeException`` thrown by ract-native

**Comment by scgough** [comment]
Wow that is an old issue then... 😄

Thanks for looking into this. The unique path value "fix" I've used seems to have helped a lot but something more solid like you mentioned would be cool sort out too.

**Comment by Saad-Bashar** [comment]
Not sure if I have the similar problem, https://github.com/RonRadtke/react-native-blob-util/issues/164
