### ISSUE TITLE
The WRITE_EXTERNAL_STORAGE permission becomes useless in Android 10

### ISSUE THREAD

**Issue by mickeylam** [RonRadtke/react-native-blob-util#23]
react-native-blob-util: '0.13.2'
react-native: '0.61.2'

As of Nov 2020, all the android app published in the Google Play needs to set the targetSdkVersion to at least 29. The "android:maxSdkVersion" setting in the manifest makes the WRITE_EXTERNAL_STORAGE in the PermissionAndroid becomes useless in Android 10.
I have been taking a while to find that in my app mergedManifest. Finally, I added this:
tools:remove="android:maxSdkVersion"
to the permission WRITE_EXTERNAL_STORAGE.

I think it needs to be fixed. Meanwhile, and support Android 11 in future.

**Comment by RonRadtke** [comment]
The current version is working well on Android 11. Tested it on my own Android 11 device. But I'm storing the files in the apps own directory and due to that it's not a problem for me.

In Android 10 and above you don't need the WRITE_EXTERNAL_STORAGE anymore due to the scoped storage. But you're write. The permissons are not exactly ocrrect. The android:maxSDKVersion has to be a 29, so it still works for Android 10.
Starting from Android 11 we would need the MANAGE_EXTERNAL_STORAGE permisson.
For additional information see here: https://developer.android.com/training/data-storage#permissions

**Comment by cristianoccazinsp** [comment]
I was targetting SDK 30 and no issues so far with `WRITE_EXTERNAL_STORAGE`.  However, after upgrading rn-fetch-blob 0.12.0 to this (0.13.6), trying to request `WRITE_EXTERNAL_STORAGE` always returns "never ask again".

How does this library interfere with file permissions?

**Comment by arunim2405** [comment]
@cristianoccazinsp facing the same weird issue, were you able to fix it?

**Comment by cristianoccazinsp** [comment]
Not really, I still see the crash from time to time, but doesn't seem to happen as often as to worry.

**Comment by glaeser-adesso** [comment]
I'm also facing the same issue, forbidding me from using this library instead of the original rn-fetch-blob.
As soon as I add the plugin (Version 0.13.2), `WRITE_EXTERNAL_STORAGE` is permanently denied (no other modifications to the project). This causes issues for other plugins relying on it.

Using Target SDK Level 29. Is there any workaround, other than staying on the unmaintained plugin?

**Comment by RonRadtke** [comment]
I published 0.13.8 right now.
This removes the max version in the manifest. I hope that this was causing the problems.
Could you please test if that helps for your cases? I can't reproduce it on my devices / with my app.

**Comment by arunim2405** [comment]
@RonRadtke I can confirm WRITE_EXTERNAL_STORAGE is NOT permanently denied anymore after the update. That bug is fixed

**Comment by RonRadtke** [comment]
@arunim2405 Glad to hear that! Thank you.
