### ISSUE TITLE
Android response info error

### ISSUE THREAD

**Issue by MuratAkbaba006** [RonRadtke/react-native-blob-util#261]
Hello, in android app when I fetched a file, respInfo don't includes status etc. information. 
its seems like this.
"respInfo": {"rnfbEncode": "path"}

**Comment by RonRadtke** [comment]
Which version are you using?Sent from Outlook for Android

**Comment by alelaru** [comment]
@MuratAkbaba006 you do not understand it because it is an error of the package. 

    "react-native": "0.71.4",
    "react-native-blob-util": "0.18.3",
    "react": "18.2.0",
    
   @RonRadtke the problem is that when installing the packages and running them into the android device sometimes .fetch() will return the correct object with all the information inside and sometimes it will return the object @MuratAkbaba006 shows.
   
   In my case i make a post request to get some data and it will download it properly

**Comment by MuratAkbaba006** [comment]
@RonRadtke I tried 0.17.2, 0.17.3, 0.18.3 versions. all of them same result.

**Comment by MuratAkbaba006** [comment]
Additionally, if the file does not exist or there is some other error on backend side. catch block  and timeout duration doesn't work. @RonRadtke

**Comment by ammarahm-ed** [comment]
I was on v0.17.3. Upgrading to 0.18.3 has fixed the issue. As i tracked it down `DeviceEventEmitter` not receiving any events. The 0.18.3 replaces that with `NativeEventEmitter` which fixes the problem. As you are facing the issue on android, the probable cause can be something similar because:

If the below event doesn't fire before `fetchBlob` method callback is called, the `respInfo` includes just `rnfbEncode:"type of encoding"`
```ts
stateEvent = eventEmitter.addListener('ReactNativeBlobUtilState', (e) => {
            if (typeof e === 'string') e = JSON.parse(e);
            if (e.taskId === taskId)
                respInfo = e;
            promise.onStateChange && promise.onStateChange(e);
        });
```
If it's still happening on android, my guess is event is not fired on time or not fired at all during fetch request sometimes.

**Comment by chubo274** [comment]
> Hello, in android app when I fetched a file, respInfo don't includes status etc. information. its seems like this. "respInfo": {"rnfbEncode": "path"}
I tried 0.17.1, 0.17.3, 0.18.3 versions. but got same issue.
have you solved it, pls help me :(

**Comment by RonRadtke** [comment]
Thank you for the patch I will take a look at and see if ai can get it integrated soon

**Comment by NishilE** [comment]
Hello, I'm still facing the issue with version 0.19.4. Unable to retrieve the response code or status code or the error messages or the success messages from the responses while downloading the PDF files.

**Comment by ChrisZilch** [comment]
We are still facing this issue on Android using RN 0.73.8, having tested on 0.19.4, 0.19.5, 0.19.8 and 0.19.11. 

Here is a snippet of our code when downloading a PDF:

```js
const configOptions: ReactNativeBlobUtilConfig = Platform.select({
  ios: { ... },
  android: {
    fileCache: true,
    appendExt: "pdf",
    addAndroidDownloads: {
      useDownloadManager: true,
      mime: "application/pdf",
      title,
      notification: false,
      path,
    },
  },
});

ReactNativeBlobUtil.config(configOptions)
  .fetch("GET", url, {
    Authorization: ...,
  })
  .then((resp) => {
    // do something with the response status
    console.log(resp.info());
  })
```
The download is successful and we can display the PDF, but when we try to read the response info all we get is
```
{"rnfbEncode": "path"}
```

It works correctly on iOS.

Any ideas why we get this issue even on the latest version?
