### ISSUE TITLE
duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by jp928** [RonRadtke/react-native-blob-util#74]
react-native-blob-util: 0.13.16
react-native: 0.66.1

```
duplicate symbols for architecture x86_64
```

**Comment by vladimixz** [comment]
@jp928 I have same error, please say how did you fix it?

**Comment by jp928** [comment]
@vladimixz I forgot to remove the deprecated rn-fetch-bolb. This will cause duplicated symbol.

**Comment by Anujmoglix** [comment]
But I am using rn-fetch-bolb in my app and it is working fine. I don't want to remove it because that functionality is working fine.

**Comment by jp928** [comment]
@Anujmoglix This library is an alternative of rn-fetch-bolb. you have to choose one to go forward not both.

**Comment by Anujmoglix** [comment]
@aallvi  use either **react-native-blob-util** or **rn-fetch-blob** . You can't use both in package.json  Try to remove  **rn-fetch-blob**  because it is not maintained now.

**Comment by luis-antonio-dev** [comment]
> @vladimixz I forgot to remove the deprecated rn-fetch-bolb. This will cause duplicated symbol.

This works for me, thank you so much

**Comment by ManosChr** [comment]
Before deleting rn-fetch-blob, you need to search for other package dependencies, otherwise it will be deleted from package.json file but not from node_modules folder.
1. Press npm list --depth=2 at project root folder and search for packages with dependency on rn-fetch-blob
2. In my case was redux-persist-filesystem-storage
3. Update redux-persist-filesystem-storage to latest version which depends on react-native-blob-util
4. npm uninstall rn-fetch-blob
