### ISSUE TITLE
iOS error: 5 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by abhi-amci** [RonRadtke/react-native-blob-util#86]
After installing this library, while trying to run the project on Xcode, I get this error-

`5 duplicate symbols for architecture x86_64`

Heavily dependent on this library, please help.

**Comment by RonRadtke** [comment]
Please check if you are also using rn-fetch-blob. Especially if you're using e.g. react-native-pd, which migrated to this lib here, you will get such errors. It is fixable by removing rn-fetch-blob

**Comment by abhi-amci** [comment]
Yes, I removed `rn-fetch-blob` and it's working now. Thanks @RonRadtke!

**Comment by Anujmoglix** [comment]
ok but I don't want to remove it because I am using that library. Now what to do ?

**Comment by RonRadtke** [comment]
Both at once doesn't work. 
The only possibility would be to rename all duplicates in one of both libs.

**Comment by anoopbk1989** [comment]
In Xcode, below your ProjectName, you have Pods. Click on Pods, and you will get list of components under **TARGETS**. Go to Build settings of both the components(react-native-blob-util and rn-fetch-blob) and set `No Common Blocks=No`

**Comment by ankitk-nimblechapps** [comment]
@anoopbk1989 it is Not working.

**Comment by ManosChr** [comment]
Before deleting rn-fetch-blob, you need to search for other package dependencies, otherwise it will be deleted from package.json file but not from node_modules folder.
1. Press npm list --depth=2 at project root folder and search for packages with dependency on rn-fetch-blob
2. In my case was redux-persist-filesystem-storage
3. Update redux-persist-filesystem-storage to latest version which depends on react-native-blob-util
4. npm uninstall rn-fetch-blob
